name: CI
on:
  pull_request:
  push:

jobs:
  main:
    env:
      BLEND: ${{ matrix.blend }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.17'
            erlang: '27.0'
            lint: true
          - elixir: '1.16'
            erlang: '26.2.5'
          - elixir: '1.15'
            erlang: '25.3.2.12'
          - elixir: '1.14'
            erlang: '24.3.4.17'
            blend: plug_1_13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        if: ${{ ! matrix.lint && ! matrix.blend }}
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v4
        if: ${{ ! matrix.lint && matrix.blend }}
        with:
          path: |
            blend/*/_build
            blend/*/deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ matrix.blend }}-${{ hashFiles(format('blend/{0}/mix.lock', matrix.blend)) }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get --check-locked
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix compile
        if: ${{ ! matrix.lint }}
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - run: mix test
